# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Vistas/Emergente_alerta_conflicto.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EmergenteConflicto(object):
    def setupUi(self, EmergenteConflicto):
        EmergenteConflicto.setObjectName("EmergenteConflicto")
        EmergenteConflicto.resize(900, 320)
        EmergenteConflicto.setModal(True)
        self.root = QtWidgets.QVBoxLayout(EmergenteConflicto)
        self.root.setContentsMargins(40, 24, 40, 32)
        self.root.setSpacing(24)
        self.root.setObjectName("root")
        self.lblMensaje = QtWidgets.QLabel(EmergenteConflicto)
        self.lblMensaje.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lblMensaje.setWordWrap(True)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        self.lblMensaje.setFont(font)
        self.lblMensaje.setObjectName("lblMensaje")
        self.root.addWidget(self.lblMensaje)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.root.addItem(spacerItem)
        self.buttonsRow = QtWidgets.QHBoxLayout()
        self.buttonsRow.setSpacing(20)
        self.buttonsRow.setObjectName("buttonsRow")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonsRow.addItem(spacerItem1)
        self.btnConfirmar = QtWidgets.QPushButton(EmergenteConflicto)
        self.btnConfirmar.setMinimumWidth(160)
        self.btnConfirmar.setMinimumHeight(44)
        self.btnConfirmar.setObjectName("btnConfirmar")
        self.buttonsRow.addWidget(self.btnConfirmar)
        self.btnCancelar = QtWidgets.QPushButton(EmergenteConflicto)
        self.btnCancelar.setMinimumWidth(160)
        self.btnCancelar.setMinimumHeight(44)
        self.btnCancelar.setObjectName("btnCancelar")
        self.buttonsRow.addWidget(self.btnCancelar)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonsRow.addItem(spacerItem2)
        self.root.addLayout(self.buttonsRow)

        self.retranslateUi(EmergenteConflicto)
        QtCore.QMetaObject.connectSlotsByName(EmergenteConflicto)

    def retranslateUi(self, EmergenteConflicto):
        _translate = QtCore.QCoreApplication.translate
        EmergenteConflicto.setWindowTitle(_translate("EmergenteConflicto", "Conflicto"))
        self.lblMensaje.setText(_translate("EmergenteConflicto", "Hay un conflicto, ¿Quieres guardar y exportarlo a un Excel?"))
        self.btnConfirmar.setText(_translate("EmergenteConflicto", "Confirmar"))
        self.btnCancelar.setText(_translate("EmergenteConflicto", "Cancelar"))
