# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Emergente_mesas.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EmergenteMesas(object):
    def setupUi(self, EmergenteMesas):
        EmergenteMesas.setObjectName("EmergenteMesas")
        EmergenteMesas.resize(900, 520)
        self.centralwidget = QtWidgets.QWidget(EmergenteMesas)
        self.centralwidget.setObjectName("centralwidget")
        self.root = QtWidgets.QVBoxLayout(self.centralwidget)
        self.root.setContentsMargins(40, 24, 40, 24)
        self.root.setSpacing(24)
        self.root.setObjectName("root")
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.root.addItem(spacerItem)
        self.lblTitulo = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lblTitulo.setFont(font)
        self.lblTitulo.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitulo.setObjectName("lblTitulo")
        self.root.addWidget(self.lblTitulo)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.root.addItem(spacerItem1)
        self.buttonsLayout = QtWidgets.QVBoxLayout()
        self.buttonsLayout.setContentsMargins(0, 0, 0, 0)
        self.buttonsLayout.setSpacing(32)
        self.buttonsLayout.setObjectName("buttonsLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.btnAutomatico = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnAutomatico.setFont(font)
        self.btnAutomatico.setObjectName("btnAutomatico")
        self.horizontalLayout_2.addWidget(self.btnAutomatico)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.buttonsLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.btnManual = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnManual.setFont(font)
        self.btnManual.setObjectName("btnManual")
        self.horizontalLayout_3.addWidget(self.btnManual)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.buttonsLayout.addLayout(self.horizontalLayout_3)
        self.root.addLayout(self.buttonsLayout)
        spacerItem6 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.root.addItem(spacerItem6)
        EmergenteMesas.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(EmergenteMesas)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 21))
        self.menubar.setObjectName("menubar")
        EmergenteMesas.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(EmergenteMesas)
        self.statusbar.setObjectName("statusbar")
        EmergenteMesas.setStatusBar(self.statusbar)

        self.retranslateUi(EmergenteMesas)
        QtCore.QMetaObject.connectSlotsByName(EmergenteMesas)

    def retranslateUi(self, EmergenteMesas):
        _translate = QtCore.QCoreApplication.translate
        EmergenteMesas.setWindowTitle(_translate("EmergenteMesas", "Emergente mesas"))
        self.lblTitulo.setText(_translate("EmergenteMesas", "¿Cómo quieres hacer las mesas?"))
        self.btnAutomatico.setText(_translate("EmergenteMesas", "AUTOMÁTICO"))
        self.btnManual.setText(_translate("EmergenteMesas", "MANUAL"))
